spring: 
    profiles: 
        active: 
        -  dev
---
spring: 
    profiles: dev
    application:
        name: microservicecloud-config-hlxd-dev
---
spring: 
    profiles: test
    application:
        name: microservicecloud-config-hlxd-test